version: 1
disable_existing_loggers: False

formatters:
  default:
    (): 'uvicorn.logging.DefaultFormatter'
    fmt: '%(asctime)s %(levelprefix)-9s %(name)s : %(message)s'
  access:
    (): 'uvicorn.logging.AccessFormatter'
    fmt: '%(asctime)s %(levelprefix)-9s : %(client_addr)s - "%(request_line)s" %(status_code)s'
  error:
    (): 'uvicorn.logging.DefaultFormatter'
    fmt: '%(asctime)s %(levelprefix)-9s %(message)s'

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout
  error:
    class: logging.StreamHandler
    formatter: error
    stream: ext://sys.stdout


loggers:
  uvicorn:
    level: INFO
  uvicorn.error:
    level: INFO
    propagate: no
    handlers:
      - error

  uvicorn.access:
    level: INFO
    propagate: False
    handlers:
      - access
root:
  level: INFO
  handlers: [default]
  propagate: false
